### ISSUE TITLE
运行reinforcement learning里的ddqn出现了错误，可能是相关配置不对，麻烦您给解答一下

### ISSUE THREAD

**Issue by bailingbird** [ljpzzz/machinelearning#6]
我是在pycharm里导入了numpy,gym,tensorflow模块，在pycharm里运行的，然后就出现了如下错误。
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-04-10 10:23:13.232651: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

**Comment by bailingbird** [comment]
> 我是在pycharm里导入了numpy,gym,tensorflow模块，在pycharm里运行的，然后就出现了如下错误。
> Traceback (most recent call last):
> File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev_pydev_bundle\pydev_import_hook.py", line 20, in do_import
> module = self._system_import(name, *args, **kwargs)
> ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
> ImportError: numpy.core.multiarray failed to import
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
> File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev_pydev_bundle\pydev_import_hook.py", line 20, in do_import
> module = self._system_import(name, *args, **kwargs)
> File "", line 980, in _find_and_load
> SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
> ImportError: numpy.core._multiarray_umath failed to import
> ImportError: numpy.core.umath failed to import
> 2019-04-10 10:23:13.232651: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

这个问题已经得到解决，是因为numpy和TensorFlow版本不对，更新了numpy版本之后，就能正常运行了
